import Link from "next/link";
import { ArrowRight, Check, ClipboardList, MessageSquare, Network, Search, Sparkles, Users, Zap } from "lucide-react";

const steps = [
  ["01", "Capture", "Process eligible messages from your connected WhatsApp sources."],
  ["02", "Understand", "Structure listings, requirements, buildings, localities, prices, and broker context."],
  ["03", "Search", "Ask for what you need in plain language across the market you already have."],
  ["04", "Discover", "Surface relevant inventory and requirements buried in other conversations."],
  ["05", "Act", "Open the source context and move directly to the broker who shared it."],
] as const;

const capabilities = [
  [Network, "Market Inbox", "A live operating view of fresh listings, requirements, broker activity, source messages, and context."],
  [Search, "Search & Match", "Search by locality, building, BHK, budget, transaction type, property type, area, freshness, or broker."],
  [Users, "Broker Network", "Understand who is active where, what they share, and how to reach them directly on WhatsApp."],
  [ClipboardList, "Clients & Deals", "Track requirements, saved candidates, client context, deal status, and follow-ups."],
  [Sparkles, "Realtor Ads Studio", "Turn verified property information into marketing content without inventing missing details."],
  [Zap, "Workspace Intelligence", "See what is moving across your market and where your team is spending time."],
] as const;

export default function BrokerLandingPage() {
  return (
    <main className="min-h-screen overflow-hidden bg-background text-text-primary">
      <header className="border-b border-border-subtle/70">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
          <Link href="/" className="flex items-center gap-3" aria-label="PropAI home"><img src="/propai-logo.svg" alt="" aria-hidden="true" className="h-10 w-10" /><span className="text-xl font-bold tracking-tight">Prop<span className="text-accent">AI</span></span></Link>
          <nav className="hidden items-center gap-7 text-sm text-text-secondary md:flex" aria-label="Primary"><a href="#how-it-works" className="transition-colors hover:text-text-primary">How it works</a><a href="#capabilities" className="transition-colors hover:text-text-primary">Capabilities</a><a href="#pricing" className="transition-colors hover:text-text-primary">Pricing</a></nav>
          <div className="flex items-center gap-3"><Link href="/auth/login" className="hidden text-sm font-semibold text-text-secondary transition-colors hover:text-text-primary sm:inline">Sign in</Link><Link href="/auth/signup" className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-accent-hover">Start using PropAI <ArrowRight className="h-4 w-4" /></Link></div>
        </div>
      </header>

      <section className="relative border-b border-border-subtle/70 px-5 py-16 lg:px-8 lg:py-28"><div className="pointer-events-none absolute -right-40 -top-44 h-[34rem] w-[34rem] rounded-full bg-accent/10 blur-3xl" aria-hidden="true" /><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[minmax(0,1.05fr)_minmax(20rem,.7fr)] lg:gap-24">
        <div><p className="mb-5 text-xs font-bold uppercase tracking-[.18em] text-accent-forest">Broker OS · powered by your WhatsApp market</p><h1 className="max-w-4xl text-5xl font-semibold leading-[.97] tracking-[-.055em] text-text-primary sm:text-6xl lg:text-8xl">Your market is already in WhatsApp. <span className="text-accent-forest">PropAI makes it searchable.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-text-secondary lg:text-xl">Turn buried listings, requirements, and broker conversations into a live workspace for finding, matching, and moving property business.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/auth/signup" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-accent px-5 py-3 text-sm font-bold text-white shadow-lg shadow-accent/15 transition hover:-translate-y-0.5 hover:bg-accent-hover">Start using PropAI <ArrowRight className="h-4 w-4" /></Link><a href="#how-it-works" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-border-strong px-5 py-3 text-sm font-bold text-text-primary transition hover:border-accent hover:bg-accent/5">See how it works <span aria-hidden="true">↓</span></a></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-xs font-semibold text-text-muted"><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-accent-forest" /> Real WhatsApp conversations</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-accent-forest" /> ₹1,499/month</span></div></div>
        <aside className="relative rounded-3xl border border-border-subtle bg-surface-raised p-6 shadow-[0_24px_70px_rgba(47,60,48,.12)] lg:p-7" aria-label="PropAI broker workflow"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-accent-forest">The broker workflow</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">From noise to next move</h2></div><span className="inline-flex items-center gap-2 text-xs font-bold text-accent"><span className="h-2 w-2 rounded-full bg-accent shadow-[0_0_0_4px_rgba(63,142,89,.12)]" /> Live</span></div><div className="my-6 h-px bg-border-subtle" /><div className="space-y-2">{[[MessageSquare, "WhatsApp groups", "Listings · requirements · signals"], [Sparkles, "PropAI market memory", "Structured · searchable · fresh"], [ArrowRight, "Your next move", "Find · match · contact · close"]].map(([Icon, title, detail], index) => <div key={String(title)}><div className={`flex items-center gap-3 rounded-xl border p-3 ${index === 1 ? "border-accent/30 bg-accent/5" : "border-transparent"}`}><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent/10 text-accent-forest"><Icon className="h-4 w-4" /></span><span><b className="block text-sm">{title}</b><small className="mt-0.5 block text-xs text-text-secondary">{detail}</small></span></div>{index < 2 && <div className="ml-7 h-4 w-px bg-border-subtle" aria-hidden="true" />}</div>)}</div><div className="mt-6 rounded-xl border border-border-subtle bg-background p-3 text-xs leading-5 text-text-secondary">Your connected WhatsApp market, organised for business.</div></aside>
      </div></section>

      <section className="border-b border-border-subtle/70 px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent-forest">The market is bigger than your groups</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Every broker only sees the conversations they&apos;re part of.</h2><p className="mt-5 text-base leading-7 text-text-secondary">PropAI turns your connected WhatsApp market into one searchable workspace, so relevant listings and requirements can surface even when they would otherwise remain buried in another conversation.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-0 overflow-hidden rounded-2xl border border-border-subtle bg-surface-raised md:grid-cols-3">{["Find properties you would otherwise miss.", "Find requirements you would otherwise miss.", "Stop digging through WhatsApp to find them."].map((text, index) => <div key={text} className={`p-6 text-center text-sm font-semibold leading-6 ${index ? "border-t border-border-subtle md:border-l md:border-t-0" : ""}`}>{text}</div>)}</div></section>

      <section id="how-it-works" className="bg-surface/60 px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="mb-12 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent-forest">From WhatsApp noise to a working market</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Your next move starts with better market memory.</h2></div><div className="grid gap-px overflow-hidden rounded-2xl border border-border-subtle bg-border-subtle md:grid-cols-3 lg:grid-cols-5">{steps.map(([number, title, description]) => <article key={number} className="bg-background p-5 lg:p-6"><div className="text-3xl font-semibold tracking-[-.05em] text-accent/35">{number}</div><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{description}</p></article>)}</div></div></section>

      <section id="capabilities" className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="mx-auto mb-12 max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent-forest">The Broker OS</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Everything your brokerage needs to move faster.</h2><p className="mt-4 text-base leading-7 text-text-secondary">Discover the market, understand it, match it, and act on it — in one workspace.</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-border-subtle bg-border-subtle md:grid-cols-2 lg:grid-cols-3">{capabilities.map(([Icon, title, description]) => <article key={title} className="bg-surface-raised p-7 transition hover:bg-accent/5"><Icon className="h-6 w-6 text-accent-forest" /><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{description}</p></article>)}</div></div></section>

      <section id="pricing" className="border-y border-border-subtle bg-surface/60 px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1fr_360px]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-accent-forest">Built for the work, not the reveal</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">We don&apos;t hide the market behind credits.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-text-secondary">PropAI charges for the system that does the work: infrastructure, continuous processing, search, intelligence, organisation, matching, market memory, and the time saved every day.</p></div><div className="rounded-2xl border border-accent/30 bg-surface-raised p-7 shadow-lg shadow-accent/5"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent-forest">Broker OS</p><div className="mt-4 flex items-end gap-2"><span className="text-5xl font-semibold tracking-[-.06em]">₹1,499</span><span className="pb-2 text-sm text-text-secondary">/ month</span></div><p className="mt-3 text-sm leading-6 text-text-secondary">One workspace for the WhatsApp market you already have.</p><Link href="/auth/signup" className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-bold text-white hover:bg-accent-hover">Start using PropAI <ArrowRight className="h-4 w-4" /></Link></div></div></section>

      <section className="bg-accent-forest px-5 py-20 text-center text-white lg:px-8 lg:py-28"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent-soft">The question to ask every morning</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">What would you have missed today?</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-white/75">The property you need may already have been posted somewhere in your connected network. PropAI helps you find the market being generated by real broker conversations — before it disappears into the scroll.</p><Link href="/auth/signup" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-accent-forest transition hover:bg-accent-soft">Make your market searchable <ArrowRight className="h-4 w-4" /></Link></div></section>

      <footer className="border-t border-border-subtle px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-text-muted sm:flex-row sm:items-center sm:justify-between"><span>PropAI Broker OS</span><span>Your WhatsApp property network, organised for business.</span></div></footer>
    </main>
  );
}
