-- Private broker-owned inventory. This is deliberately separate from market evidence.
create table if not exists public.crm_inventory (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  created_by uuid,
  inventory_date date,
  building_name text not null default '',
  location text not null default '',
  tower text not null default '',
  bhk text not null default '',
  floor text not null default '',
  area_sqft numeric,
  quote text not null default '',
  furnishing text not null default '',
  amenities text not null default '',
  owner_name text not null default '',
  availability text not null default '',
  pets_okay text not null default '',
  contact_name text not null default '',
  contact_number text not null default '',
  notes text not null default '',
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_inventory_tenant_created_idx
  on public.crm_inventory (tenant_id, created_at desc);
create index if not exists crm_inventory_tenant_location_idx
  on public.crm_inventory (tenant_id, location);

alter table public.crm_inventory enable row level security;

drop policy if exists crm_inventory_tenant_read on public.crm_inventory;
create policy crm_inventory_tenant_read on public.crm_inventory
  for select to authenticated
  using (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));

drop policy if exists crm_inventory_tenant_write on public.crm_inventory;
create policy crm_inventory_tenant_write on public.crm_inventory
  for all to authenticated
  using (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()))
  with check (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));

drop policy if exists crm_inventory_service_role on public.crm_inventory;
create policy crm_inventory_service_role on public.crm_inventory
  for all to service_role using (true) with check (true);
