-- Durable, broker-controlled policy for deterministic requirement matching.
-- IDs are typed-table IDs and intentionally use a discriminator rather than a
-- cross-table foreign key, matching requirement_matches' identity contract.
create table if not exists public.requirement_match_preferences (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  requirement_type text not null check (requirement_type in ('residential_rent','residential_sale','commercial_rent','commercial_sale')),
  requirement_typed_id bigint not null,
  minimum_score numeric not null default 50 check (minimum_score between 0 and 100),
  max_matches integer not null default 5 check (max_matches between 1 and 50),
  freshness_days integer not null default 30 check (freshness_days between 1 and 365),
  area_tolerance_percent numeric not null default 20 check (area_tolerance_percent between 0 and 100),
  budget_tolerance_percent numeric not null default 0 check (budget_tolerance_percent between 0 and 100),
  allow_missing_bhk boolean not null default false,
  allow_missing_price boolean not null default true,
  allow_missing_area boolean not null default true,
  enabled boolean not null default true,
  cadence_minutes integer not null default 15 check (cadence_minutes between 5 and 1440),
  notify_enabled boolean not null default false,
  next_run_at timestamptz not null default now(),
  last_run_at timestamptz,
  last_run_status text,
  last_run_metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, requirement_type, requirement_typed_id)
);

create index if not exists requirement_match_preferences_due_idx
  on public.requirement_match_preferences (tenant_id, enabled, next_run_at);

alter table public.requirement_match_preferences enable row level security;
drop policy if exists service_role_all_requirement_match_preferences on public.requirement_match_preferences;
create policy service_role_all_requirement_match_preferences
  on public.requirement_match_preferences for all to service_role using (true) with check (true);

comment on table public.requirement_match_preferences is
  'Per-requirement deterministic matcher policy; no LLM or automatic outreach is implied.';

alter table public.requirement_matches
  add column if not exists match_reasons text[] not null default '{}',
  add column if not exists unknown_fields text[] not null default '{}';
