insert into storage.buckets (id, name, public)
values ('private-crm', 'private-crm', false)
on conflict (id) do update set public = false;

create table if not exists public.crm_inventory_attachments (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  inventory_id bigint references public.crm_inventory(id) on delete cascade,
  created_by uuid not null,
  storage_bucket text not null default 'private-crm',
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null,
  extracted_text text not null default '',
  text_supported boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists crm_inventory_attachments_tenant_idx
  on public.crm_inventory_attachments (tenant_id, created_at desc);
create index if not exists crm_inventory_attachments_inventory_idx
  on public.crm_inventory_attachments (inventory_id);

alter table public.crm_inventory_attachments enable row level security;

drop policy if exists crm_inventory_attachments_tenant_select on public.crm_inventory_attachments;
create policy crm_inventory_attachments_tenant_select
  on public.crm_inventory_attachments for select
  using (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));

drop policy if exists crm_inventory_attachments_tenant_insert on public.crm_inventory_attachments;
create policy crm_inventory_attachments_tenant_insert
  on public.crm_inventory_attachments for insert
  with check (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));

drop policy if exists crm_inventory_attachments_service_role on public.crm_inventory_attachments;
create policy crm_inventory_attachments_service_role
  on public.crm_inventory_attachments for all to service_role
  using (true) with check (true);
