-- Typed extraction destination schema.
-- This migration intentionally renames the old destinations at the end.
-- Application code must be cut over to the typed tables before ingestion resumes.

begin;

create or replace function public._typed_num(v text)
returns numeric language sql immutable as $$
  select case when nullif(trim(v), '') is null then null
    when trim(v) ~ '^-?[0-9]+(\.[0-9]+)?$' then trim(v)::numeric end
$$;

create or replace function public._typed_money(v numeric, unit text)
returns numeric language sql immutable as $$
  select case lower(coalesce(unit, ''))
    when 'cr' then v * 10000000
    when 'crore' then v * 10000000
    when 'lac' then v * 100000
    when 'lakh' then v * 100000
    when 'k' then v * 1000
    when 'thousand' then v * 1000
    else v end
$$;

create or replace function public._typed_asset(asset text, property text, body text)
returns text language sql immutable as $$
  select case
    when lower(coalesce(asset,'') || ' ' || coalesce(property,'') || ' ' || coalesce(body,'')) ~
      '(office|shop|showroom|warehouse|godown|industrial|commercial|retail|bare.?shell|warm.?shell|chargeable area|ceiling height|mezzanine|cabin|workstation|conference room|\bpsf\b|\bcam\b|lease deed|power load|\bkw\b|food court)'
      then 'commercial'
    else 'residential'
  end
$$;

create or replace function public._typed_tx(intent text, tx text, body text)
returns text language sql immutable as $$
  select case
    when lower(coalesce(tx,'') || ' ' || coalesce(intent,'') || ' ' || coalesce(body,'')) ~
      '(rent|rental|lease|monthly|per month|deposit|tenancy|lock.?in|notice period|lease out)' then 'rent'
    else 'sale'
  end
$$;

-- Every table has an explicit provenance fingerprint so the backfill is rerunnable.
create table if not exists public.residential_sale_listings (
  id bigint generated always as identity primary key, raw_message_id bigint not null references public.raw_messages(id) on delete cascade,
  tenant_id uuid references public.organizations(id), listing_index integer not null default 0, source_fingerprint text not null unique,
  asset_type text not null default 'residential' check (asset_type='residential'), transaction_type text not null default 'sale' check (transaction_type='sale'),
  building_name text, locality_raw text, locality_resolved text, micro_market text, locality_confidence text default 'low' check (locality_confidence in ('high','medium','low')), landmark_name text, street_name text,
  broker_id bigint references public.brokers(id), broker_name text, broker_phone text, group_name text,
  summary_title text, normalized_message text, raw_payload jsonb default '{}'::jsonb, ai_extraction jsonb, deal_tags text[] default '{}', additional_charges jsonb default '[]', validation_flags jsonb default '[]', needs_review boolean not null default false, extraction_confidence text default 'medium' check (extraction_confidence in ('high','medium','low')), corrected_fields text[] default '{}', correction_confidence numeric, corrected_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), legacy_source_id bigint,
  bhk numeric check (bhk is null or bhk>0), configuration_type text, bathroom_count integer, carpet_area_sqft numeric, built_up_area_sqft numeric, super_built_up_area_sqft numeric, area_raw_text text,
  total_asking_price numeric, price_per_sqft numeric, price_basis text, price_raw_text text, price_qualifier text,
  stamp_duty_amount numeric, stamp_duty_applicable boolean, registration_amount numeric, registration_applicable boolean, gst_amount numeric, gst_applicable boolean, gst_rate numeric, plc_amount numeric, plc_applicable boolean, plc_per_sqft numeric, floor_rise_amount numeric, floor_rise_applicable boolean, floor_rise_per_sqft numeric, society_transfer_amount numeric, society_transfer_applicable boolean, development_charges_amount numeric, development_charges_applicable boolean, sinking_fund_amount numeric, sinking_fund_applicable boolean, property_tax_annual numeric, property_tax_applicable boolean,
  token_amount numeric, payment_plan text, payment_plan_details text, transaction_nature text, furnishing_status text, possession_status text, possession_date date, age_of_property text, car_parking_count integer, parking_type text, floor_range text, building_amenities text[] default '{}', unit_amenities text[] default '{}', amenities_unverified_claim text, oc_status text, rera_registered boolean, rera_number text, bank_loan_eligible boolean, title_status text, occupancy_status text, property_view text, orientation text, society_restrictions text[] default '{}', society_maintenance_amount numeric, society_maintenance_applicable boolean, society_maintenance_unit text, brokerage_type text, developer_name text
);

create table if not exists public.residential_rent_listings (
  id bigint generated always as identity primary key, raw_message_id bigint not null references public.raw_messages(id) on delete cascade, tenant_id uuid references public.organizations(id), listing_index integer not null default 0, source_fingerprint text not null unique,
  asset_type text not null default 'residential' check (asset_type='residential'), transaction_type text not null default 'rent' check (transaction_type='rent'),
  building_name text, locality_raw text, locality_resolved text, micro_market text, locality_confidence text default 'low' check (locality_confidence in ('high','medium','low')), landmark_name text, street_name text, broker_id bigint references public.brokers(id), broker_name text, broker_phone text, group_name text, summary_title text, normalized_message text, raw_payload jsonb default '{}', ai_extraction jsonb, deal_tags text[] default '{}', additional_charges jsonb default '[]', validation_flags jsonb default '[]', needs_review boolean not null default false, extraction_confidence text default 'medium' check (extraction_confidence in ('high','medium','low')), corrected_fields text[] default '{}', correction_confidence numeric, corrected_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), legacy_source_id bigint,
  bhk numeric, configuration_type text, bathroom_count integer, carpet_area_sqft numeric, built_up_area_sqft numeric, area_raw_text text, monthly_rent numeric, rent_per_sqft numeric, price_basis text, price_raw_text text, price_qualifier text, deposit_amount numeric, deposit_months numeric, deposit_applicable boolean, deposit_raw_text text, furnishing_status text, possession_status text, available_from date, car_parking_count integer, parking_type text, floor_range text, building_amenities text[] default '{}', unit_amenities text[] default '{}', amenities_unverified_claim text, pet_policy text, tenant_type_preference text, sharing_allowed text, tenant_nationality_preference text, company_lease_criteria jsonb, food_preference text, lease_term_type text, lock_in_period_months integer, notice_period_months integer, society_restrictions text[] default '{}', painting_charges_rule text, society_maintenance_amount numeric, society_maintenance_applicable boolean, society_maintenance_unit text, electricity_type text, property_view text, brokerage_type text
);

create table if not exists public.commercial_sale_listings (
  id bigint generated always as identity primary key, raw_message_id bigint not null references public.raw_messages(id) on delete cascade, tenant_id uuid references public.organizations(id), listing_index integer not null default 0, source_fingerprint text not null unique,
  asset_type text not null default 'commercial' check (asset_type='commercial'), transaction_type text not null default 'sale' check (transaction_type='sale'),
  building_name text, locality_raw text, locality_resolved text, micro_market text, locality_confidence text default 'low' check (locality_confidence in ('high','medium','low')), landmark_name text, street_name text, broker_id bigint references public.brokers(id), broker_name text, broker_phone text, group_name text, summary_title text, normalized_message text, raw_payload jsonb default '{}', ai_extraction jsonb, deal_tags text[] default '{}', additional_charges jsonb default '[]', validation_flags jsonb default '[]', needs_review boolean not null default false, extraction_confidence text default 'medium' check (extraction_confidence in ('high','medium','low')), corrected_fields text[] default '{}', correction_confidence numeric, corrected_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), legacy_source_id bigint,
  commercial_use_type text not null default 'mixed_use', carpet_area_sqft numeric, built_up_area_sqft numeric, chargeable_area_sqft numeric, super_built_up_area_sqft numeric, mezzanine_area_sqft numeric, saleable_area_sqft numeric, area_raw_text text, total_asking_price numeric, price_per_sqft numeric, price_basis text, price_raw_text text, price_qualifier text, stamp_duty_amount numeric, stamp_duty_applicable boolean, registration_amount numeric, registration_applicable boolean, gst_amount numeric, gst_applicable boolean, gst_rate numeric, plc_amount numeric, plc_applicable boolean, floor_rise_amount numeric, floor_rise_applicable boolean, society_transfer_amount numeric, society_transfer_applicable boolean, development_charges_amount numeric, development_charges_applicable boolean, property_tax_annual numeric, property_tax_applicable boolean, token_amount numeric, payment_plan text, payment_plan_details text, transaction_nature text, fitout_status text, ceiling_height text, floor_level text, floor_range text, floor_count integer, has_mezzanine boolean default false, has_staircase boolean default false, car_parking_count integer, parking_type text, parking_charges_amount numeric, parking_charges_applicable boolean, parking_charges_unit text, oc_status text, rera_registered boolean, rera_number text, bank_loan_eligible boolean, title_status text, occupancy_status text, building_amenities text[] default '{}', has_central_ac boolean, has_power_backup boolean, has_lift boolean, lift_count integer, cabin_count integer, workstation_count integer, conference_room_count integer, meeting_room_count integer, washroom_count integer, pantry_type text, reception_area boolean default false, server_room boolean default false, storage_area boolean default false, power_load_kw numeric, society_maintenance_amount numeric, society_maintenance_applicable boolean, brokerage_type text, developer_name text
);

create table if not exists public.commercial_rent_listings (
  id bigint generated always as identity primary key, raw_message_id bigint not null references public.raw_messages(id) on delete cascade, tenant_id uuid references public.organizations(id), listing_index integer not null default 0, source_fingerprint text not null unique,
  asset_type text not null default 'commercial' check (asset_type='commercial'), transaction_type text not null default 'rent' check (transaction_type='rent'),
  building_name text, locality_raw text, locality_resolved text, micro_market text, locality_confidence text default 'low' check (locality_confidence in ('high','medium','low')), landmark_name text, street_name text, broker_id bigint references public.brokers(id), broker_name text, broker_phone text, group_name text, summary_title text, normalized_message text, raw_payload jsonb default '{}', ai_extraction jsonb, deal_tags text[] default '{}', additional_charges jsonb default '[]', validation_flags jsonb default '[]', needs_review boolean not null default false, extraction_confidence text default 'medium' check (extraction_confidence in ('high','medium','low')), corrected_fields text[] default '{}', correction_confidence numeric, corrected_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), legacy_source_id bigint,
  commercial_use_type text not null default 'mixed_use', carpet_area_sqft numeric, built_up_area_sqft numeric, chargeable_area_sqft numeric, mezzanine_area_sqft numeric, area_raw_text text, monthly_rent numeric, rent_per_sqft numeric, price_basis text, price_raw_text text, price_qualifier text, deposit_amount numeric, deposit_months numeric, deposit_applicable boolean, deposit_raw_text text, fitout_status text, ceiling_height text, floor_level text, floor_range text, floor_count integer, has_mezzanine boolean default false, car_parking_count integer, parking_type text, parking_charges_amount numeric, parking_charges_applicable boolean, parking_charges_unit text, oc_status text, building_amenities text[] default '{}', has_central_ac boolean, has_power_backup boolean, has_lift boolean, cabin_count integer, workstation_count integer, conference_room_count integer, meeting_room_count integer, washroom_count integer, pantry_type text, reception_area boolean default false, server_room boolean default false, storage_area boolean default false, power_load_kw numeric, cam_amount numeric, cam_applicable boolean, cam_unit text, society_maintenance_amount numeric, society_maintenance_applicable boolean, property_tax_amount numeric, property_tax_applicable boolean, electricity_type text, lease_term_type text, lock_in_period_months integer, notice_period_months integer, escalation_pct numeric, escalation_frequency text, escalation_type text, rent_free_period_months integer, fitout_period_months integer, lease_deed_type text, sub_leasing_allowed boolean, brokerage_type text
);

-- Requirement envelope and type-specific demand fields.
create table if not exists public.residential_sale_requirements (like public.residential_sale_listings including defaults excluding constraints, constraint residential_sale_requirements_asset check (asset_type='residential'), constraint residential_sale_requirements_tx check (transaction_type='sale'), constraint residential_sale_requirements_pk primary key (id));
alter table public.residential_sale_requirements alter column id add generated by default as identity;
alter table public.residential_sale_requirements drop column if exists total_asking_price, drop column if exists price_per_sqft, drop column if exists price_basis, drop column if exists price_raw_text, drop column if exists price_qualifier;
alter table public.residential_sale_requirements add column if not exists budget_min numeric, add column if not exists budget_max numeric, add column if not exists budget_currency text default 'INR', add column if not exists area_min_sqft numeric, add column if not exists area_max_sqft numeric, add column if not exists locality_options text[] default '{}', add column if not exists is_flexible boolean default false, add column if not exists urgency text, add column if not exists status text default 'active', add column if not exists bhk_options numeric[] default '{}', add column if not exists configuration_preference text[] default '{}', add column if not exists carpet_area_min_sqft numeric, add column if not exists carpet_area_max_sqft numeric, add column if not exists built_up_area_min_sqft numeric, add column if not exists built_up_area_max_sqft numeric, add column if not exists budget_per_sqft_max numeric, add column if not exists furnishing_preference text, add column if not exists possession_preference text, add column if not exists age_preference text, add column if not exists micro_market_options text[] default '{}', add column if not exists building_preferences text[] default '{}', add column if not exists car_parking_min integer, add column if not exists floor_preference text, add column if not exists view_preference text[] default '{}', add column if not exists amenity_requirements text[] default '{}', add column if not exists buyer_type text, add column if not exists nationality text, add column if not exists loan_preapproved boolean, add column if not exists transaction_nature text, add column if not exists brokerage_willingness text;

create table if not exists public.residential_rent_requirements (like public.residential_sale_requirements including defaults excluding constraints, constraint residential_rent_requirements_asset check (asset_type='residential'), constraint residential_rent_requirements_tx check (transaction_type='rent'), constraint residential_rent_requirements_pk primary key (id));
alter table public.residential_rent_requirements alter column id add generated by default as identity;
alter table public.residential_rent_requirements add column if not exists deposit_budget_max numeric, add column if not exists available_from date, add column if not exists tenant_type text, add column if not exists has_pets boolean default false, add column if not exists sharing_acceptable boolean default false, add column if not exists food_preference text, add column if not exists lease_term_preference text;

create table if not exists public.commercial_sale_requirements (like public.residential_sale_requirements including defaults excluding constraints, constraint commercial_sale_requirements_asset check (asset_type='commercial'), constraint commercial_sale_requirements_tx check (transaction_type='sale'), constraint commercial_sale_requirements_pk primary key (id));
alter table public.commercial_sale_requirements alter column id add generated by default as identity;
alter table public.commercial_sale_requirements add column if not exists commercial_use_type text[] default '{}', add column if not exists chargeable_area_max_sqft numeric, add column if not exists fitout_preference text, add column if not exists min_ceiling_height text, add column if not exists needs_mezzanine boolean default false, add column if not exists needs_lift boolean default false, add column if not exists needs_power_backup boolean default false, add column if not exists needs_central_ac boolean default false, add column if not exists min_power_load_kw numeric, add column if not exists oc_required boolean default true;

create table if not exists public.commercial_rent_requirements (like public.commercial_sale_requirements including defaults excluding constraints, constraint commercial_rent_requirements_asset check (asset_type='commercial'), constraint commercial_rent_requirements_tx check (transaction_type='rent'), constraint commercial_rent_requirements_pk primary key (id));
alter table public.commercial_rent_requirements alter column id add generated by default as identity;
alter table public.commercial_rent_requirements add column if not exists deposit_budget_max numeric, add column if not exists budget_per_sqft_max numeric, add column if not exists min_cabin_count integer, add column if not exists min_workstation_count integer, add column if not exists needs_conference_room boolean default false, add column if not exists needs_pantry boolean default false, add column if not exists needs_server_room boolean default false, add column if not exists lease_term_preference text, add column if not exists max_lock_in_months integer, add column if not exists max_notice_period_months integer, add column if not exists company_type text, add column if not exists team_size integer;

-- Add the requirement envelope constraints after LIKE-based creation.
do $$ declare t text; begin foreach t in array array['residential_sale_requirements','residential_rent_requirements','commercial_sale_requirements','commercial_rent_requirements'] loop
  execute format('alter table public.%I add constraint %I check (urgency is null or urgency in (''urgent'',''normal'',''flexible''))', t, t||'_urgency');
  execute format('alter table public.%I add constraint %I check (status is null or status in (''active'',''fulfilled'',''expired'',''withdrawn''))', t, t||'_status');
end loop; exception when duplicate_object then null; end $$;

-- Backfill typed listings from parsed_output. NULL asset_type is classified from the
-- raw message; those rows are deliberately marked for review.
with src as (
  select p.*, r.message as source_message, lower(coalesce(p.asset_type,'') || ' ' || coalesce(p.property_type,'')) as source_type,
    public._typed_asset(p.asset_type,p.property_type,r.message) as a,
    public._typed_tx(p.intent,p.transaction_type,r.message) as tx,
    coalesce(p.carpet_area_sqft, public._typed_num(p.ai_extraction->>'carpet_area_sqft'), p.area_sqft) as carpet,
    coalesce(p.built_up_area_sqft, public._typed_num(p.ai_extraction->>'built_up_area_sqft')) as built,
    coalesce(p.total_asking_price,p.monthly_rent,public._typed_money(p.price,p.price_unit)) as amount,
    case when lower(coalesce(p.price_unit,''))='psf' then p.price end as psf
  from public.parsed_output p left join public.raw_messages r on r.id=p.raw_message_id
  where lower(coalesce(p.message_type,'')) not in ('buy','requirement') and lower(coalesce(p.intent,'')) not in ('buy','requirement','buyer')
), ins as (
  select src.*, md5('parsed_output:'||id::text) fp from src
)
insert into public.residential_sale_listings (raw_message_id,tenant_id,listing_index,source_fingerprint,building_name,locality_raw,locality_resolved,micro_market,landmark_name,street_name,broker_id,broker_name,broker_phone,group_name,summary_title,normalized_message,raw_payload,ai_extraction,deal_tags,additional_charges,validation_flags,needs_review,extraction_confidence,corrected_fields,correction_confidence,corrected_at,created_at,updated_at,legacy_source_id,bhk,configuration_type,bathroom_count,carpet_area_sqft,built_up_area_sqft,area_raw_text,total_asking_price,price_per_sqft,price_basis,price_raw_text,furnishing_status,possession_status,possession_date,car_parking_count,parking_type,floor_range,amenities_unverified_claim,oc_status,brokerage_type,developer_name)
select raw_message_id,tenant_id,coalesce(listing_index,0),fp,building_name,location_raw,location_raw,micro_market,landmark_name,street_name,case when exists(select 1 from brokers b where b.id=src.broker_id) then src.broker_id end,broker_name,broker_phone,group_name,summary_title,normalized_message,coalesce(raw_payload,'{}'),ai_extraction,coalesce(deal_tags,'{}'),coalesce(additional_charges,'[]'),coalesce(validation_flags,'[]'),needs_review or asset_type is null or (tx='sale' and amount is null),case when confidence>=.8 then 'high' when confidence>=.5 then 'medium' else 'low' end,coalesce(corrected_fields,'{}'),correction_confidence,corrected_at,created_at,now(),id,public._typed_num(regexp_replace(coalesce(bhk,''),'[^0-9.]','','g')),configuration_type,bathroom_count,carpet,built,area,case when a='residential' and tx='sale' then amount end,psf,price_basis,ai_extraction->'price'->>'raw_price_text',furnishing_canonical,possession_status,case when possession_date ~ '^\d{4}-\d{2}-\d{2}$' then possession_date::date end,car_parking_count,parking_type,floor_range,amenities_unverified_claim,oc_status,brokerage_type,developer
from ins src where a='residential' and tx='sale';

with src as (select p.*,r.message source_message,public._typed_asset(p.asset_type,p.property_type,r.message) a,public._typed_tx(p.intent,p.transaction_type,r.message) tx,coalesce(p.carpet_area_sqft,public._typed_num(p.ai_extraction->>'carpet_area_sqft'),p.area_sqft) carpet,coalesce(p.built_up_area_sqft,public._typed_num(p.ai_extraction->>'built_up_area_sqft')) built,coalesce(p.monthly_rent,public._typed_money(p.price,p.price_unit)) amount,md5('parsed_output:'||p.id::text) fp from public.parsed_output p left join public.raw_messages r on r.id=p.raw_message_id where lower(coalesce(p.message_type,'')) not in ('buy','requirement') and lower(coalesce(p.intent,'')) not in ('buy','requirement','buyer'))
insert into public.residential_rent_listings (raw_message_id,tenant_id,listing_index,source_fingerprint,building_name,locality_raw,locality_resolved,micro_market,landmark_name,street_name,broker_id,broker_name,broker_phone,group_name,summary_title,normalized_message,raw_payload,ai_extraction,deal_tags,additional_charges,validation_flags,needs_review,extraction_confidence,corrected_fields,correction_confidence,corrected_at,created_at,updated_at,legacy_source_id,bhk,configuration_type,bathroom_count,carpet_area_sqft,built_up_area_sqft,area_raw_text,monthly_rent,rent_per_sqft,price_basis,price_raw_text,deposit_amount,furnishing_status,possession_status,available_from,car_parking_count,parking_type,floor_range,amenities_unverified_claim,pet_policy,tenant_type_preference,sharing_allowed,tenant_nationality_preference,company_lease_criteria,food_preference,lease_term_type,brokerage_type)
select raw_message_id,tenant_id,coalesce(listing_index,0),fp,building_name,location_raw,location_raw,micro_market,landmark_name,street_name,case when exists(select 1 from brokers b where b.id=src.broker_id) then src.broker_id end,broker_name,broker_phone,group_name,summary_title,normalized_message,coalesce(raw_payload,'{}'),ai_extraction,coalesce(deal_tags,'{}'),coalesce(additional_charges,'[]'),coalesce(validation_flags,'[]'),needs_review or asset_type is null or amount is null,case when confidence>=.8 then 'high' when confidence>=.5 then 'medium' else 'low' end,coalesce(corrected_fields,'{}'),correction_confidence,corrected_at,created_at,now(),id,public._typed_num(regexp_replace(coalesce(bhk,''),'[^0-9.]','','g')),configuration_type,bathroom_count,carpet,built,area,amount,null,price_basis,ai_extraction->'price'->>'raw_price_text',deposit_amount,furnishing_canonical,possession_status,case when available_from ~ '^\d{4}-\d{2}-\d{2}$' then available_from::date end,car_parking_count,parking_type,floor_range,amenities_unverified_claim,pet_policy,tenant_type_preference,sharing_allowed,tenant_nationality_preference,company_lease_criteria,null,lease_term_type,brokerage_type
from src where a='residential' and tx='rent';

with src as (select p.*,r.message source_message,public._typed_asset(p.asset_type,p.property_type,r.message) a,public._typed_tx(p.intent,p.transaction_type,r.message) tx,coalesce(p.carpet_area_sqft,public._typed_num(p.ai_extraction->>'carpet_area_sqft'),p.area_sqft) carpet,coalesce(p.built_up_area_sqft,public._typed_num(p.ai_extraction->>'built_up_area_sqft')) built,coalesce(p.total_asking_price,p.monthly_rent,public._typed_money(p.price,p.price_unit)) amount,md5('parsed_output:'||p.id::text) fp from public.parsed_output p left join public.raw_messages r on r.id=p.raw_message_id where lower(coalesce(p.message_type,'')) not in ('buy','requirement') and lower(coalesce(p.intent,'')) not in ('buy','requirement','buyer'))
insert into public.commercial_sale_listings (raw_message_id,tenant_id,listing_index,source_fingerprint,building_name,locality_raw,locality_resolved,micro_market,landmark_name,street_name,broker_id,broker_name,broker_phone,group_name,summary_title,normalized_message,raw_payload,ai_extraction,deal_tags,additional_charges,validation_flags,needs_review,extraction_confidence,corrected_fields,correction_confidence,corrected_at,created_at,updated_at,legacy_source_id,commercial_use_type,carpet_area_sqft,built_up_area_sqft,area_raw_text,total_asking_price,price_per_sqft,price_basis,price_raw_text,fitout_status,ceiling_height,floor_level,floor_range,car_parking_count,parking_type,oc_status,brokerage_type,developer_name)
select raw_message_id,tenant_id,coalesce(listing_index,0),fp,building_name,location_raw,location_raw,micro_market,landmark_name,street_name,case when exists(select 1 from brokers b where b.id=src.broker_id) then src.broker_id end,broker_name,broker_phone,group_name,summary_title,normalized_message,coalesce(raw_payload,'{}'),ai_extraction,coalesce(deal_tags,'{}'),coalesce(additional_charges,'[]'),coalesce(validation_flags,'[]'),true or needs_review or asset_type is null or commercial_use_type is null,case when confidence>=.8 then 'high' when confidence>=.5 then 'medium' else 'low' end,coalesce(corrected_fields,'{}'),correction_confidence,corrected_at,created_at,now(),id,coalesce(nullif(lower(commercial_use_type),''),'mixed_use'),carpet,built,area,amount,null,price_basis,ai_extraction->'price'->>'raw_price_text',fitout_status,ceiling_height,floor_range,floor_range,car_parking_count,parking_type,oc_status,brokerage_type,developer
from src where a='commercial' and tx='sale';

with src as (select p.*,r.message source_message,public._typed_asset(p.asset_type,p.property_type,r.message) a,public._typed_tx(p.intent,p.transaction_type,r.message) tx,coalesce(p.carpet_area_sqft,public._typed_num(p.ai_extraction->>'carpet_area_sqft'),p.area_sqft) carpet,coalesce(p.built_up_area_sqft,public._typed_num(p.ai_extraction->>'built_up_area_sqft')) built,coalesce(p.monthly_rent,public._typed_money(p.price,p.price_unit)) amount,md5('parsed_output:'||p.id::text) fp from public.parsed_output p left join public.raw_messages r on r.id=p.raw_message_id where lower(coalesce(p.message_type,'')) not in ('buy','requirement') and lower(coalesce(p.intent,'')) not in ('buy','requirement','buyer'))
insert into public.commercial_rent_listings (raw_message_id,tenant_id,listing_index,source_fingerprint,building_name,locality_raw,locality_resolved,micro_market,landmark_name,street_name,broker_id,broker_name,broker_phone,group_name,summary_title,normalized_message,raw_payload,ai_extraction,deal_tags,additional_charges,validation_flags,needs_review,extraction_confidence,corrected_fields,correction_confidence,corrected_at,created_at,updated_at,legacy_source_id,commercial_use_type,carpet_area_sqft,built_up_area_sqft,area_raw_text,monthly_rent,price_basis,price_raw_text,deposit_amount,fitout_status,ceiling_height,floor_level,floor_range,car_parking_count,parking_type,oc_status,brokerage_type)
select raw_message_id,tenant_id,coalesce(listing_index,0),fp,building_name,location_raw,location_raw,micro_market,landmark_name,street_name,case when exists(select 1 from brokers b where b.id=src.broker_id) then src.broker_id end,broker_name,broker_phone,group_name,summary_title,normalized_message,coalesce(raw_payload,'{}'),ai_extraction,coalesce(deal_tags,'{}'),coalesce(additional_charges,'[]'),coalesce(validation_flags,'[]'),true or needs_review or asset_type is null or commercial_use_type is null or amount is null,case when confidence>=.8 then 'high' when confidence>=.5 then 'medium' else 'low' end,coalesce(corrected_fields,'{}'),correction_confidence,corrected_at,created_at,now(),id,coalesce(nullif(lower(commercial_use_type),''),'mixed_use'),carpet,built,area,amount,price_basis,ai_extraction->'price'->>'raw_price_text',deposit_amount,fitout_status,ceiling_height,floor_range,floor_range,car_parking_count,parking_type,oc_status,brokerage_type
from src where a='commercial' and tx='rent';

-- Requirements are copied from the already-promoted market_requirements table.
with req as (select mr.*,coalesce(nullif(lower(mr.transaction_type),''),public._typed_tx(mr.intent,'',rm.message)) tx,public._typed_asset(po.asset_type,po.property_type,rm.message) a,po.ai_extraction,po.raw_payload,po.deal_tags,po.additional_charges,po.validation_flags,po.summary_title,po.normalized_message,po.corrected_fields,po.correction_confidence,po.corrected_at,po.created_at po_created,po.message_type from public.market_requirements mr left join lateral (select p.* from public.parsed_output p where p.raw_message_id=mr.raw_message_id and lower(coalesce(p.message_type,'')) in ('buy','requirement') order by p.id desc limit 1) po on true left join public.raw_messages rm on rm.id=mr.raw_message_id)
insert into public.residential_sale_requirements (raw_message_id,tenant_id,listing_index,source_fingerprint,asset_type,transaction_type,building_name,locality_raw,locality_resolved,micro_market,landmark_name,broker_id,broker_name,broker_phone,group_name,summary_title,normalized_message,raw_payload,ai_extraction,deal_tags,additional_charges,validation_flags,needs_review,extraction_confidence,corrected_fields,correction_confidence,corrected_at,created_at,updated_at,legacy_source_id,budget_min,budget_max,budget_currency,area_min_sqft,area_max_sqft,locality_options,is_flexible,urgency,status,bhk_options,carpet_area_min_sqft,carpet_area_max_sqft,built_up_area_min_sqft,built_up_area_max_sqft)
select raw_message_id,tenant_id,0,md5('market_requirements:'||id::text),coalesce(a,'residential'),tx,building_name,location_label,location_label,micro_market,landmark_name,case when exists(select 1 from brokers b where b.id=mr.broker_id) then mr.broker_id end,broker_name,broker_phone, null,summary_title,normalized_message,coalesce(raw_payload,'{}'),ai_extraction,coalesce(deal_tags,'{}'),coalesce(additional_charges,'[]'),coalesce(validation_flags,'[]'),true,case when confidence>=.8 then 'high' when confidence>=.5 then 'medium' else 'low' end,coalesce(corrected_fields,'{}'),correction_confidence,corrected_at,coalesce(po_created,created_at),now(),id,price_min,price_max,'INR',area_sqft,area_sqft,case when location_label is null then '{}' else array[location_label] end,false,null,'active',case when bhk ~ '[0-9]' then array[public._typed_num(regexp_replace(bhk,'[^0-9.]','','g'))]::numeric[] else '{}' end,area_sqft,area_sqft,area_sqft,area_sqft
from req mr where tx='sale' and a<>'commercial';

with req as (select mr.*,coalesce(nullif(lower(mr.transaction_type),''),public._typed_tx(mr.intent,'',rm.message)) tx,public._typed_asset(po.asset_type,po.property_type,rm.message) a,po.summary_title,po.normalized_message,po.raw_payload,po.ai_extraction,po.deal_tags,po.additional_charges,po.validation_flags,po.corrected_fields,po.correction_confidence,po.corrected_at,po.created_at po_created from public.market_requirements mr left join lateral (select p.* from public.parsed_output p where p.raw_message_id=mr.raw_message_id and lower(coalesce(p.message_type,'')) in ('buy','requirement') order by p.id desc limit 1) po on true left join public.raw_messages rm on rm.id=mr.raw_message_id)
insert into public.residential_rent_requirements (raw_message_id,tenant_id,listing_index,source_fingerprint,asset_type,transaction_type,building_name,locality_raw,locality_resolved,micro_market,broker_id,broker_name,broker_phone,summary_title,normalized_message,raw_payload,ai_extraction,deal_tags,additional_charges,validation_flags,needs_review,extraction_confidence,created_at,updated_at,budget_min,budget_max,budget_currency,area_min_sqft,area_max_sqft,locality_options,status,bhk_options,carpet_area_min_sqft,carpet_area_max_sqft,deposit_budget_max)
select raw_message_id,tenant_id,0,md5('market_requirements:'||id::text),coalesce(a,'residential'),tx,building_name,location_label,location_label,micro_market,broker_id,broker_name,broker_phone,summary_title,normalized_message,coalesce(raw_payload,'{}'),ai_extraction,coalesce(deal_tags,'{}'),coalesce(additional_charges,'[]'),coalesce(validation_flags,'[]'),true,case when confidence>=.8 then 'high' when confidence>=.5 then 'medium' else 'low' end,coalesce(po_created,created_at),now(),price_min,price_max,'INR',area_sqft,area_sqft,case when location_label is null then '{}' else array[location_label] end,'active',case when bhk ~ '[0-9]' then array[public._typed_num(regexp_replace(bhk,'[^0-9.]','','g'))]::numeric[] else '{}' end,area_sqft,area_sqft,null
from req where tx='rent' and a<>'commercial';

-- Commercial requirement copies use the same provenance and shared fields; the
-- type-specific commercial fields remain null until the focused extraction bridge.
insert into public.commercial_sale_requirements (raw_message_id,tenant_id,listing_index,source_fingerprint,asset_type,transaction_type,building_name,locality_raw,locality_resolved,micro_market,broker_id,broker_name,broker_phone,raw_payload,needs_review,extraction_confidence,created_at,updated_at,budget_min,budget_max,budget_currency,area_min_sqft,area_max_sqft,status,commercial_use_type)
select mr.raw_message_id,mr.tenant_id,0,md5('market_requirements:'||mr.id::text), 'commercial','sale',mr.building_name,mr.location_label,mr.location_label,mr.micro_market,mr.broker_id,mr.broker_name,mr.broker_phone,'{}',true,'low',mr.created_at,now(),mr.price_min,mr.price_max,'INR',mr.area_sqft,mr.area_sqft,'active',array[]::text[] from public.market_requirements mr left join public.raw_messages rm on rm.id=mr.raw_message_id where coalesce(lower(nullif(mr.transaction_type,'')),public._typed_tx(mr.intent,'',rm.message))='sale' and exists(select 1 from parsed_output p where p.raw_message_id=mr.raw_message_id and public._typed_asset(p.asset_type,p.property_type,rm.message)='commercial') and not exists(select 1 from public.commercial_sale_requirements q where q.raw_message_id=mr.raw_message_id);
insert into public.commercial_rent_requirements (raw_message_id,tenant_id,listing_index,source_fingerprint,asset_type,transaction_type,building_name,locality_raw,locality_resolved,micro_market,broker_id,broker_name,broker_phone,raw_payload,needs_review,extraction_confidence,created_at,updated_at,budget_min,budget_max,budget_currency,area_min_sqft,area_max_sqft,status,commercial_use_type)
select mr.raw_message_id,mr.tenant_id,0,md5('market_requirements:'||mr.id::text), 'commercial','rent',mr.building_name,mr.location_label,mr.location_label,mr.micro_market,mr.broker_id,mr.broker_name,mr.broker_phone,'{}',true,'low',mr.created_at,now(),mr.price_min,mr.price_max,'INR',mr.area_sqft,mr.area_sqft,'active',array[]::text[] from public.market_requirements mr left join public.raw_messages rm on rm.id=mr.raw_message_id where coalesce(lower(nullif(mr.transaction_type,'')),public._typed_tx(mr.intent,'',rm.message))='rent' and exists(select 1 from parsed_output p where p.raw_message_id=mr.raw_message_id and public._typed_asset(p.asset_type,p.property_type,rm.message)='commercial') and not exists(select 1 from public.commercial_rent_requirements q where q.raw_message_id=mr.raw_message_id);

-- Backfill review flags for missing critical fields and suspicious price-period mixes.
update public.residential_sale_listings set needs_review=true where total_asking_price is null and price_per_sqft is null;
update public.residential_rent_listings set needs_review=true where monthly_rent is null and rent_per_sqft is null;
update public.commercial_sale_listings set needs_review=true where total_asking_price is null and price_per_sqft is null;
update public.commercial_rent_listings set needs_review=true where monthly_rent is null and rent_per_sqft is null;

do $$ declare t text; begin foreach t in array array['residential_sale_listings','residential_rent_listings','commercial_sale_listings','commercial_rent_listings','residential_sale_requirements','residential_rent_requirements','commercial_sale_requirements','commercial_rent_requirements'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('drop policy if exists service_role_all_%I on public.%I',t,t);
  execute format('create policy service_role_all_%I on public.%I for all to service_role using (true) with check (true)',t,t);
  execute format('create index if not exists idx_%I_tenant on public.%I(tenant_id)',t,t);
  execute format('create index if not exists idx_%I_raw on public.%I(raw_message_id)',t,t);
  execute format('create index if not exists idx_%I_created on public.%I(created_at desc)',t,t);
  execute format('create index if not exists idx_%I_review on public.%I(needs_review) where needs_review=true',t,t);
  execute format('create index if not exists idx_%I_locality on public.%I(micro_market)',t,t);
end loop; end $$;
create index if not exists idx_res_sale_price_typed on public.residential_sale_listings(total_asking_price);
create index if not exists idx_res_rent_price_typed on public.residential_rent_listings(monthly_rent);
create index if not exists idx_comm_sale_price_typed on public.commercial_sale_listings(total_asking_price);
create index if not exists idx_comm_rent_price_typed on public.commercial_rent_listings(monthly_rent);
create index if not exists idx_res_sale_req_bhk on public.residential_sale_requirements using gin(bhk_options);
create index if not exists idx_res_rent_req_bhk on public.residential_rent_requirements using gin(bhk_options);
create unique index if not exists uq_res_sale_source on public.residential_sale_listings(source_fingerprint);
create unique index if not exists uq_res_rent_source on public.residential_rent_listings(source_fingerprint);
create unique index if not exists uq_comm_sale_source on public.commercial_sale_listings(source_fingerprint);
create unique index if not exists uq_comm_rent_source on public.commercial_rent_listings(source_fingerprint);
create unique index if not exists uq_res_sale_req_source on public.residential_sale_requirements(source_fingerprint);
create unique index if not exists uq_res_rent_req_source on public.residential_rent_requirements(source_fingerprint);
create unique index if not exists uq_comm_sale_req_source on public.commercial_sale_requirements(source_fingerprint);
create unique index if not exists uq_comm_rent_req_source on public.commercial_rent_requirements(source_fingerprint);

drop view if exists public.parsed_output_unified;
create view public.parsed_output_unified as
select 'residential_sale' card_type,id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,bhk::text bhk,carpet_area_sqft area_sqft,total_asking_price price,'sale' transaction_type,needs_review,created_at from public.residential_sale_listings
union all select 'residential_rent',id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,bhk::text,carpet_area_sqft,monthly_rent,'rent',needs_review,created_at from public.residential_rent_listings
union all select 'commercial_sale',id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,null,carpet_area_sqft,total_asking_price,'sale',needs_review,created_at from public.commercial_sale_listings
union all select 'commercial_rent',id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,null,carpet_area_sqft,monthly_rent,'rent',needs_review,created_at from public.commercial_rent_listings;

drop view if exists public.requirements_unified;
create view public.requirements_unified as
select 'residential_sale' req_type,id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,bhk_options,budget_min,budget_max,carpet_area_min_sqft,carpet_area_max_sqft,status,created_at from public.residential_sale_requirements
union all select 'residential_rent',id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,bhk_options,budget_min,budget_max,carpet_area_min_sqft,carpet_area_max_sqft,status,created_at from public.residential_rent_requirements
union all select 'commercial_sale',id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,'{}',budget_min,budget_max,carpet_area_min_sqft,carpet_area_max_sqft,status,created_at from public.commercial_sale_requirements
union all select 'commercial_rent',id,raw_message_id,tenant_id,building_name,micro_market,broker_name,broker_phone,'{}',budget_min,budget_max,carpet_area_min_sqft,carpet_area_max_sqft,status,created_at from public.commercial_rent_requirements;

-- Preserve the old data exactly, but make the old names unavailable so accidental
-- writes cannot silently populate the deprecated schema after this cutover.
alter table public.parsed_output rename to parsed_output_legacy;
alter table public.listings rename to listings_legacy;
alter table public.market_requirements rename to market_requirements_legacy;

insert into supabase_migrations.schema_migrations(version,name) values ('20260803020000','typed_extraction_schemas') on conflict (version) do nothing;
commit;
