-- The public site reads these views directly.  Keep them live projections of
-- the typed tables so newly extracted rows are visible without a backfill or
-- a second indexing pipeline.

drop view if exists public.parsed_output_unified;
drop view if exists public.listings_unified;

create view public.listings_unified
with (security_invoker = true)
as
select
  'residential_sale'::text as card_type,
  r.id,
  r.raw_message_id,
  r.tenant_id,
  r.building_name,
  r.micro_market,
  r.broker_name,
  r.broker_phone,
  r.bhk::text as bhk,
  coalesce(r.carpet_area_sqft, r.built_up_area_sqft) as area_sqft,
  case
    when r.price_per_sqft is not null and coalesce(r.carpet_area_sqft, r.built_up_area_sqft) is not null
      then r.price_per_sqft * coalesce(r.carpet_area_sqft, r.built_up_area_sqft)
    else r.total_asking_price
  end as price,
  'abs'::text as price_unit,
  case when r.price_per_sqft is not null then 'psf' else 'one_time' end::text as price_model,
  r.price_per_sqft,
  r.furnishing_status as furnishing,
  r.furnishing_status,
  null::text as fitout_status,
  r.floor_range as floor_description,
  r.property_view as view,
  r.property_view,
  coalesce(r.locality_raw, r.locality_resolved, r.micro_market) as location_label,
  r.locality_raw,
  r.locality_resolved,
  r.locality_confidence,
  r.landmark_name,
  r.street_name,
  r.group_name,
  r.summary_title,
  r.normalized_message,
  coalesce(r.raw_payload ->> 'full_text', r.normalized_message) as raw_message,
  coalesce(r.broker_name, r.broker_phone) as raw_sender,
  r.raw_payload,
  r.ai_extraction,
  r.deal_tags,
  r.additional_charges,
  r.validation_flags,
  r.needs_review,
  r.extraction_confidence,
  r.corrected_fields,
  r.correction_confidence,
  r.corrected_at,
  r.created_at,
  coalesce(r.updated_at, r.created_at) as updated_at,
  r.created_at as first_seen,
  coalesce(r.updated_at, r.created_at) as last_seen,
  1::bigint as observation_count,
  1::bigint as group_count,
  r.raw_message_id as representative_raw_message_id,
  r.raw_message_id as latest_raw_message_id,
  r.listing_index as representative_listing_index,
  nullif(trim(both '-' from regexp_replace(lower(coalesce(r.micro_market, r.locality_resolved, r.locality_raw, '')), '[^a-z0-9]+', '-', 'g')), '') as canonical_micro_market_slug,
  r.price_raw_text,
  r.price_qualifier,
  r.carpet_area_sqft,
  r.built_up_area_sqft,
  r.listing_index as listing_index,
  r.source_fingerprint,
  'residential'::text as asset_type,
  'residential'::text as property_type,
  'SELL'::text as intent,
  'sale'::text as transaction_type,
  r.transaction_nature,
  r.broker_id
from public.residential_sale_listings r

union all

select
  'residential_rent'::text,
  r.id,
  r.raw_message_id,
  r.tenant_id,
  r.building_name,
  r.micro_market,
  r.broker_name,
  r.broker_phone,
  r.bhk::text,
  coalesce(r.carpet_area_sqft, r.built_up_area_sqft),
  case
    when r.rent_per_sqft is not null and coalesce(r.carpet_area_sqft, r.built_up_area_sqft) is not null
      then r.rent_per_sqft * coalesce(r.carpet_area_sqft, r.built_up_area_sqft)
    else r.monthly_rent
  end,
  'abs'::text,
  case when r.rent_per_sqft is not null then 'psf' else 'per_month' end::text,
  r.rent_per_sqft,
  r.furnishing_status,
  r.furnishing_status,
  null::text,
  r.floor_range,
  r.property_view,
  r.property_view,
  coalesce(r.locality_raw, r.locality_resolved, r.micro_market),
  r.locality_raw,
  r.locality_resolved,
  r.locality_confidence,
  r.landmark_name,
  r.street_name,
  r.group_name,
  r.summary_title,
  r.normalized_message,
  coalesce(r.raw_payload ->> 'full_text', r.normalized_message),
  coalesce(r.broker_name, r.broker_phone),
  r.raw_payload,
  r.ai_extraction,
  r.deal_tags,
  r.additional_charges,
  r.validation_flags,
  r.needs_review,
  r.extraction_confidence,
  r.corrected_fields,
  r.correction_confidence,
  r.corrected_at,
  r.created_at,
  coalesce(r.updated_at, r.created_at),
  r.created_at,
  coalesce(r.updated_at, r.created_at),
  1::bigint,
  1::bigint,
  r.raw_message_id,
  r.raw_message_id,
  r.listing_index,
  nullif(trim(both '-' from regexp_replace(lower(coalesce(r.micro_market, r.locality_resolved, r.locality_raw, '')), '[^a-z0-9]+', '-', 'g')), ''),
  r.price_raw_text,
  r.price_qualifier,
  r.carpet_area_sqft,
  r.built_up_area_sqft,
  r.listing_index,
  r.source_fingerprint,
  'residential'::text,
  'residential'::text,
  'RENT'::text,
  'rent'::text,
  null::text,
  r.broker_id
from public.residential_rent_listings r

union all

select
  'commercial_sale'::text,
  r.id,
  r.raw_message_id,
  r.tenant_id,
  r.building_name,
  r.micro_market,
  r.broker_name,
  r.broker_phone,
  null::text,
  coalesce(r.carpet_area_sqft, r.built_up_area_sqft, r.chargeable_area_sqft, r.saleable_area_sqft),
  case
    when r.price_per_sqft is not null and coalesce(r.carpet_area_sqft, r.built_up_area_sqft, r.chargeable_area_sqft, r.saleable_area_sqft) is not null
      then r.price_per_sqft * coalesce(r.carpet_area_sqft, r.built_up_area_sqft, r.chargeable_area_sqft, r.saleable_area_sqft)
    else r.total_asking_price
  end,
  'abs'::text,
  case when r.price_per_sqft is not null then 'psf' else 'one_time' end::text,
  r.price_per_sqft,
  r.fitout_status,
  null::text,
  r.fitout_status,
  coalesce(r.floor_level, r.floor_range),
  null::text,
  null::text,
  coalesce(r.locality_raw, r.locality_resolved, r.micro_market),
  r.locality_raw,
  r.locality_resolved,
  r.locality_confidence,
  r.landmark_name,
  r.street_name,
  r.group_name,
  r.summary_title,
  r.normalized_message,
  coalesce(r.raw_payload ->> 'full_text', r.normalized_message),
  coalesce(r.broker_name, r.broker_phone),
  r.raw_payload,
  r.ai_extraction,
  r.deal_tags,
  r.additional_charges,
  r.validation_flags,
  r.needs_review,
  r.extraction_confidence,
  r.corrected_fields,
  r.correction_confidence,
  r.corrected_at,
  r.created_at,
  coalesce(r.updated_at, r.created_at),
  r.created_at,
  coalesce(r.updated_at, r.created_at),
  1::bigint,
  1::bigint,
  r.raw_message_id,
  r.raw_message_id,
  r.listing_index,
  nullif(trim(both '-' from regexp_replace(lower(coalesce(r.micro_market, r.locality_resolved, r.locality_raw, '')), '[^a-z0-9]+', '-', 'g')), ''),
  r.price_raw_text,
  r.price_qualifier,
  r.carpet_area_sqft,
  r.built_up_area_sqft,
  r.listing_index,
  r.source_fingerprint,
  'commercial'::text,
  'commercial'::text,
  'SELL'::text,
  'sale'::text,
  r.transaction_nature,
  r.broker_id
from public.commercial_sale_listings r

union all

select
  'commercial_rent'::text,
  r.id,
  r.raw_message_id,
  r.tenant_id,
  r.building_name,
  r.micro_market,
  r.broker_name,
  r.broker_phone,
  null::text,
  coalesce(r.carpet_area_sqft, r.built_up_area_sqft, r.chargeable_area_sqft),
  case
    when r.rent_per_sqft is not null and coalesce(r.carpet_area_sqft, r.built_up_area_sqft, r.chargeable_area_sqft) is not null
      then r.rent_per_sqft * coalesce(r.carpet_area_sqft, r.built_up_area_sqft, r.chargeable_area_sqft)
    else r.monthly_rent
  end,
  'abs'::text,
  case when r.rent_per_sqft is not null then 'psf' else 'per_month' end::text,
  r.rent_per_sqft,
  r.fitout_status,
  null::text,
  r.fitout_status,
  coalesce(r.floor_level, r.floor_range),
  null::text,
  null::text,
  coalesce(r.locality_raw, r.locality_resolved, r.micro_market),
  r.locality_raw,
  r.locality_resolved,
  r.locality_confidence,
  r.landmark_name,
  r.street_name,
  r.group_name,
  r.summary_title,
  r.normalized_message,
  coalesce(r.raw_payload ->> 'full_text', r.normalized_message),
  coalesce(r.broker_name, r.broker_phone),
  r.raw_payload,
  r.ai_extraction,
  r.deal_tags,
  r.additional_charges,
  r.validation_flags,
  r.needs_review,
  r.extraction_confidence,
  r.corrected_fields,
  r.correction_confidence,
  r.corrected_at,
  r.created_at,
  coalesce(r.updated_at, r.created_at),
  r.created_at,
  coalesce(r.updated_at, r.created_at),
  1::bigint,
  1::bigint,
  r.raw_message_id,
  r.raw_message_id,
  r.listing_index,
  nullif(trim(both '-' from regexp_replace(lower(coalesce(r.micro_market, r.locality_resolved, r.locality_raw, '')), '[^a-z0-9]+', '-', 'g')), ''),
  r.price_raw_text,
  r.price_qualifier,
  r.carpet_area_sqft,
  r.built_up_area_sqft,
  r.listing_index,
  r.source_fingerprint,
  'commercial'::text,
  'commercial'::text,
  'RENT'::text,
  'rent'::text,
  null::text,
  r.broker_id
from public.commercial_rent_listings r;

create view public.parsed_output_unified
with (security_invoker = true)
as
select * from public.listings_unified;

grant select on public.listings_unified to anon, authenticated, service_role;
grant select on public.parsed_output_unified to anon, authenticated, service_role;

notify pgrst, 'reload schema';
