-- Broker-controlled bridge from My Deals into deterministic Auto Match.
-- Typed source IDs remain local to their source table and are identified by
-- source_type; no legacy listing/requirement FK is introduced.
create table if not exists public.matching_item_approvals (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  item_kind text not null check (item_kind in ('listing','requirement')),
  source_type text not null check (source_type in ('residential_rent','residential_sale','commercial_rent','commercial_sale')),
  source_id bigint not null,
  owner_user_id uuid,
  client_id bigint references public.clients(id) on delete set null,
  approved boolean not null default false,
  visibility text not null default 'workspace_private' check (visibility in ('workspace_private','team','shared_market')),
  approved_at timestamptz,
  approved_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, item_kind, source_type, source_id)
);

create index if not exists matching_item_approvals_lookup_idx
  on public.matching_item_approvals (tenant_id, item_kind, approved, source_type, source_id);
create index if not exists matching_item_approvals_owner_idx
  on public.matching_item_approvals (tenant_id, owner_user_id, approved);

create table if not exists public.match_buckets (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  owner_user_id uuid,
  name text not null,
  bucket_kind text not null check (bucket_kind in ('listings','requirements')),
  visibility text not null default 'workspace_private' check (visibility in ('workspace_private','team','shared_market')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists match_buckets_scope_idx
  on public.match_buckets (tenant_id, owner_user_id, bucket_kind, updated_at desc);

create table if not exists public.match_bucket_items (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  bucket_id bigint not null references public.match_buckets(id) on delete cascade,
  source_type text not null check (source_type in ('residential_rent','residential_sale','commercial_rent','commercial_sale')),
  source_id bigint not null,
  added_by uuid,
  created_at timestamptz not null default now(),
  unique (bucket_id, source_type, source_id)
);

create index if not exists match_bucket_items_scope_idx
  on public.match_bucket_items (tenant_id, bucket_id, source_type, source_id);

alter table public.matching_item_approvals enable row level security;
alter table public.match_buckets enable row level security;
alter table public.match_bucket_items enable row level security;
do $$ begin
  execute 'create policy service_role_all_matching_item_approvals on public.matching_item_approvals for all to service_role using (true) with check (true)';
exception when duplicate_object then null; end $$;
do $$ begin
  execute 'create policy service_role_all_match_buckets on public.match_buckets for all to service_role using (true) with check (true)';
exception when duplicate_object then null; end $$;
do $$ begin
  execute 'create policy service_role_all_match_bucket_items on public.match_bucket_items for all to service_role using (true) with check (true)';
exception when duplicate_object then null; end $$;
