create extension if not exists vector with schema extensions;

create table if not exists public.semantic_embeddings (
  id bigint generated by default as identity primary key,
  tenant_id uuid,
  entity_type text not null check (entity_type in (
    'listing', 'requirement', 'building', 'building_alias',
    'locality', 'broker', 'broker_alias'
  )),
  source_table text not null,
  source_id bigint not null,
  model text not null,
  dimensions integer not null default 1024 check (dimensions = 1024),
  content text not null,
  content_hash text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(1024) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_table, source_id, model)
);

create index if not exists semantic_embeddings_tenant_type_idx
  on public.semantic_embeddings (tenant_id, entity_type);
create index if not exists semantic_embeddings_source_idx
  on public.semantic_embeddings (source_table, source_id);
create index if not exists semantic_embeddings_hnsw_idx
  on public.semantic_embeddings using hnsw (embedding vector_cosine_ops)
  with (m = 16, ef_construction = 64);

create table if not exists public.semantic_embedding_jobs (
  id bigint generated by default as identity primary key,
  tenant_id uuid,
  entity_type text not null,
  source_table text not null,
  source_id bigint not null,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'completed', 'failed')),
  attempts integer not null default 0,
  last_error text,
  scheduled_after timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_table, source_id)
);

create index if not exists semantic_embedding_jobs_pending_idx
  on public.semantic_embedding_jobs (status, scheduled_after, id)
  where status in ('pending', 'failed');

alter table public.semantic_embeddings enable row level security;
alter table public.semantic_embedding_jobs enable row level security;
revoke all on public.semantic_embeddings from anon, authenticated;
revoke all on public.semantic_embedding_jobs from anon, authenticated;
grant all on public.semantic_embeddings to service_role;
grant all on public.semantic_embedding_jobs to service_role;

create or replace function public.queue_semantic_embedding()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_entity_type text;
  v_tenant_id uuid;
begin
  if tg_op = 'DELETE' then
    delete from public.semantic_embeddings
     where source_table = tg_table_name and source_id = old.id;
    delete from public.semantic_embedding_jobs
     where source_table = tg_table_name and source_id = old.id;
    return old;
  end if;

  v_entity_type := case
    when tg_table_name like '%_listings' then 'listing'
    when tg_table_name like '%_requirements' then 'requirement'
    when tg_table_name = 'buildings' then 'building'
    when tg_table_name = 'building_name_aliases' then 'building_alias'
    when tg_table_name = 'locality_reference' then 'locality'
    when tg_table_name = 'brokers' then 'broker'
    when tg_table_name = 'broker_aliases' then 'broker_alias'
    else null
  end;
  if v_entity_type is null then return new; end if;

  v_tenant_id := case
    when tg_table_name = 'locality_reference' then null
    else nullif(to_jsonb(new)->>'tenant_id', '')::uuid
  end;

  insert into public.semantic_embedding_jobs
    (tenant_id, entity_type, source_table, source_id, status, attempts,
     last_error, scheduled_after, started_at, completed_at, updated_at)
  values
    (v_tenant_id, v_entity_type, tg_table_name, new.id, 'pending', 0,
     null, now(), null, null, now())
  on conflict (source_table, source_id) do update set
    tenant_id = excluded.tenant_id,
    entity_type = excluded.entity_type,
    status = 'pending',
    attempts = 0,
    last_error = null,
    scheduled_after = now(),
    started_at = null,
    completed_at = null,
    updated_at = now();
  return new;
end;
$$;

do $$
declare
  t text;
begin
  foreach t in array array[
    'residential_sale_listings', 'residential_rent_listings',
    'commercial_sale_listings', 'commercial_rent_listings',
    'residential_sale_requirements', 'residential_rent_requirements',
    'commercial_sale_requirements', 'commercial_rent_requirements',
    'buildings', 'building_name_aliases', 'locality_reference',
    'brokers', 'broker_aliases'
  ] loop
    execute format('drop trigger if exists queue_semantic_embedding on public.%I', t);
    execute format(
      'create trigger queue_semantic_embedding after insert or update or delete on public.%I '
      'for each row execute function public.queue_semantic_embedding()', t
    );
  end loop;
end $$;

create or replace function public.match_semantic_embeddings(
  p_query_embedding text,
  p_entity_types text[] default null,
  p_tenant_id uuid default null,
  p_limit integer default 20,
  p_min_similarity real default 0.25,
  p_model text default null
)
returns table (
  entity_type text,
  source_table text,
  source_id bigint,
  tenant_id uuid,
  similarity real,
  content text,
  metadata jsonb
)
language sql
stable
security invoker
set search_path = public, extensions, pg_temp
as $$
  select e.entity_type, e.source_table, e.source_id, e.tenant_id,
         (1 - (e.embedding <=> p_query_embedding::extensions.vector))::real,
         e.content, e.metadata
    from public.semantic_embeddings e
   where (p_entity_types is null or e.entity_type = any(p_entity_types))
     and (
       e.tenant_id is null
       or e.tenant_id = p_tenant_id
       or (
         e.entity_type in ('listing', 'requirement')
         and e.metadata->>'visibility' = 'shared_market'
       )
     )
     and (p_model is null or e.model = p_model)
     and 1 - (e.embedding <=> p_query_embedding::extensions.vector) >= p_min_similarity
   order by e.embedding <=> p_query_embedding::extensions.vector
   limit least(greatest(coalesce(p_limit, 20), 1), 100)
$$;

revoke all on function public.match_semantic_embeddings(text,text[],uuid,integer,real,text)
  from public, anon, authenticated;
grant execute on function public.match_semantic_embeddings(text,text[],uuid,integer,real,text)
  to service_role;

create or replace function public.enqueue_semantic_backfill(p_limit integer default 100)
returns integer
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  spec record;
  inserted_count integer;
  total_count integer := 0;
  freshness_sql text;
begin
  for spec in
    select * from (values
      ('residential_sale_listings', 'listing'), ('residential_rent_listings', 'listing'),
      ('commercial_sale_listings', 'listing'), ('commercial_rent_listings', 'listing'),
      ('residential_sale_requirements', 'requirement'), ('residential_rent_requirements', 'requirement'),
      ('commercial_sale_requirements', 'requirement'), ('commercial_rent_requirements', 'requirement'),
      ('buildings', 'building'), ('building_name_aliases', 'building_alias'),
      ('locality_reference', 'locality'), ('brokers', 'broker'), ('broker_aliases', 'broker_alias')
    ) as s(table_name, entity_type)
  loop
    freshness_sql := case
      when spec.entity_type in ('listing', 'requirement')
        then ' and coalesce(s.updated_at, s.created_at) >= now() - interval ''30 days'' '
      else ''
    end;
    execute format(
      'insert into public.semantic_embedding_jobs (tenant_id, entity_type, source_table, source_id) '
      'select %s, %L, %L, s.id from public.%I s '
      'where not exists (select 1 from public.semantic_embedding_jobs j where j.source_table=%L and j.source_id=s.id) %s '
      'order by s.id desc limit %s on conflict (source_table, source_id) do nothing',
      case when spec.table_name = 'locality_reference' then 'null' else 's.tenant_id' end,
      spec.entity_type, spec.table_name, spec.table_name, spec.table_name,
      freshness_sql, least(greatest(coalesce(p_limit, 100), 1), 500)
    );
    get diagnostics inserted_count = row_count;
    total_count := total_count + inserted_count;
  end loop;
  return total_count;
end;
$$;
revoke all on function public.enqueue_semantic_backfill(integer) from public, anon, authenticated;
grant execute on function public.enqueue_semantic_backfill(integer) to service_role;

-- Seed bounded, high-value entities immediately. Typed inventory is backfilled
-- separately by the worker in fresh-first batches to avoid a production spike.
insert into public.semantic_embedding_jobs
  (tenant_id, entity_type, source_table, source_id)
select tenant_id, 'building', 'buildings', id from public.buildings
order by updated_at desc nulls last, id desc limit 500
on conflict (source_table, source_id) do nothing;
insert into public.semantic_embedding_jobs
  (tenant_id, entity_type, source_table, source_id)
select null, 'locality', 'locality_reference', id from public.locality_reference
order by updated_at desc nulls last, id desc limit 500
on conflict (source_table, source_id) do nothing;
insert into public.semantic_embedding_jobs
  (tenant_id, entity_type, source_table, source_id)
select tenant_id, 'broker', 'brokers', id from public.brokers
order by updated_at desc nulls last, id desc limit 500
on conflict (source_table, source_id) do nothing;
