alter table public.crm_inventory add column if not exists custom_fields jsonb not null default '{}'::jsonb;
alter table public.crm_inventory add column if not exists transaction_type text not null default '';
alter table public.crm_inventory add column if not exists asset_type text not null default '';

create table if not exists public.crm_inventory_fields (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  field_key text not null,
  label text not null,
  field_type text not null default 'text',
  options jsonb not null default '[]'::jsonb,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (tenant_id, field_key)
);

alter table public.crm_inventory_fields enable row level security;
create policy crm_inventory_fields_tenant_access on public.crm_inventory_fields for all to authenticated
  using (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()))
  with check (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));
create policy crm_inventory_fields_service_role on public.crm_inventory_fields for all to service_role using (true) with check (true);
