-- Team members for workspace access control.

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  email text default '',
  phone text default '',
  role text not null default 'member',
  permissions integer not null default 0,
  is_active integer not null default 1,
  linked_broker_phone text default null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Custom roles (user-defined permission templates)
create table if not exists public.team_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  permission_keys jsonb not null default '[]',
  is_system boolean not null default false,
  created_at timestamptz not null default now()
);

-- Seed default system roles (mirrors the 4 fixed roles)
insert into public.team_roles (name, permission_keys, is_system) values
  ('owner', '["view_inbox","reply_whatsapp","save_requirements","save_listings","export_contacts","view_broker_numbers","add_team_members","delete_data","ai_actions","bulk_broadcast"]', true),
  ('admin', '["view_inbox","reply_whatsapp","save_requirements","save_listings","export_contacts","view_broker_numbers","add_team_members","ai_actions"]', true),
  ('member', '["view_inbox","reply_whatsapp","save_requirements","save_listings","export_contacts"]', true),
  ('intern', '["view_inbox"]', true)
on conflict (name) do nothing;

alter table public.team_members enable row level security;
alter table public.team_roles enable row level security;

create policy "Service role has full access to team_members"
  on public.team_members to service_role
  using (true) with check (true);

create policy "Service role has full access to team_roles"
  on public.team_roles to service_role
  using (true) with check (true);
