-- User profiles for onboarding data.
-- Phone number (from WhatsApp) is the primary identity.

create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  phone text not null unique,
  first_name text not null,
  last_name text not null default '',
  email text not null default '',
  city text not null default '',
  onboarding_complete boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;

create policy "Service role has full access to user_profiles"
  on public.user_profiles
  to service_role
  using (true)
  with check (true);
