-- Broker-controlled outbound inventory exports. These tables contain OAuth
-- credentials and must never be exposed through the public site.

create table if not exists public.google_drive_oauth_states (
  state text primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null,
  code_verifier text not null,
  redirect_uri text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.google_drive_connections (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null unique references public.organizations(id) on delete cascade,
  google_subject text not null,
  google_email text not null default '',
  access_token_encrypted text,
  access_token_expires_at timestamptz,
  refresh_token_encrypted text not null,
  scopes text[] not null default '{}',
  status text not null default 'connected',
  last_validated_at timestamptz,
  revoked_at timestamptz,
  connected_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.google_drive_exports (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  connection_id bigint not null references public.google_drive_connections(id) on delete cascade,
  folder_id text,
  file_id text,
  file_name text not null default 'PropAI Inventory - Current',
  inventory_ids jsonb not null default '[]'::jsonb,
  status text not null default 'active',
  last_checksum text,
  last_row_count integer not null default 0,
  last_attempted_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, file_name)
);

create table if not exists public.google_drive_sync_jobs (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.organizations(id) on delete cascade,
  export_id bigint not null references public.google_drive_exports(id) on delete cascade,
  reason text not null default 'inventory_changed',
  status text not null default 'pending',
  attempts integer not null default 0,
  scheduled_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists google_drive_exports_due_idx
  on public.google_drive_exports (status, updated_at desc);
create index if not exists google_drive_sync_jobs_due_idx
  on public.google_drive_sync_jobs (status, scheduled_at, id);
create unique index if not exists google_drive_sync_jobs_one_open_idx
  on public.google_drive_sync_jobs (export_id)
  where status in ('pending', 'running');

alter table public.google_drive_oauth_states enable row level security;
alter table public.google_drive_connections enable row level security;
alter table public.google_drive_exports enable row level security;
alter table public.google_drive_sync_jobs enable row level security;

drop policy if exists google_drive_oauth_states_service_role on public.google_drive_oauth_states;
create policy google_drive_oauth_states_service_role on public.google_drive_oauth_states for all to service_role using (true) with check (true);

drop policy if exists google_drive_connections_tenant on public.google_drive_connections;
create policy google_drive_connections_tenant on public.google_drive_connections for all to authenticated
  using (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()))
  with check (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));
drop policy if exists google_drive_exports_tenant on public.google_drive_exports;
create policy google_drive_exports_tenant on public.google_drive_exports for all to authenticated
  using (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()))
  with check (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));
drop policy if exists google_drive_sync_jobs_tenant on public.google_drive_sync_jobs;
create policy google_drive_sync_jobs_tenant on public.google_drive_sync_jobs for all to authenticated
  using (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()))
  with check (public.is_super_admin() or tenant_id = any(select public.user_tenant_ids()));

drop policy if exists google_drive_service_role on public.google_drive_connections;
create policy google_drive_service_role on public.google_drive_connections for all to service_role using (true) with check (true);
drop policy if exists google_drive_exports_service_role on public.google_drive_exports;
create policy google_drive_exports_service_role on public.google_drive_exports for all to service_role using (true) with check (true);
drop policy if exists google_drive_sync_jobs_service_role on public.google_drive_sync_jobs;
create policy google_drive_sync_jobs_service_role on public.google_drive_sync_jobs for all to service_role using (true) with check (true);
