-- Public editorial content is separate from WhatsApp-sourced market inventory.
-- Drafts stay private; only explicitly published posts are public and crawlable.
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null default '',
  category text not null default 'Property guides',
  cover_image_url text,
  seo_title text,
  seo_description text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blog_posts_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint blog_posts_published_at check (status = 'draft' or published_at is not null)
);

create index if not exists idx_blog_posts_publication
  on public.blog_posts (status, published_at desc);

alter table public.blog_posts enable row level security;

drop policy if exists blog_posts_public_read on public.blog_posts;
create policy blog_posts_public_read on public.blog_posts
  for select to anon, authenticated
  using (status = 'published' and published_at <= now());

revoke all on public.blog_posts from anon, authenticated;
grant select on public.blog_posts to anon, authenticated;
grant all on public.blog_posts to service_role;

-- Keep timestamps correct for edits made through the Super Admin table API.
drop trigger if exists blog_posts_touch_updated_at on public.blog_posts;
create trigger blog_posts_touch_updated_at
before update on public.blog_posts
for each row execute function public.trigger_set_updated_at();

notify pgrst, 'reload schema';
