-- Audit storage for deterministic historical source-evidence corrections.
create table if not exists public.extraction_backfill_audit (
  id bigint generated by default as identity primary key,
  source_table text not null,
  source_row_id bigint not null,
  raw_message_id bigint,
  field_name text not null,
  old_value jsonb,
  new_value jsonb,
  flags_added jsonb not null default '[]'::jsonb,
  backfill_run_id uuid not null,
  applied_at timestamptz not null default now()
);

create index if not exists idx_extraction_backfill_audit_run
  on public.extraction_backfill_audit (backfill_run_id, source_table, source_row_id);

create or replace view public.extraction_needs_review as
select 'residential_sale_listings'::text as source_table, id as source_row_id,
       raw_message_id, validation_flags, corrected_fields, corrected_at,
       needs_review, created_at
from public.residential_sale_listings where needs_review = true
union all
select 'residential_rent_listings', id, raw_message_id, validation_flags,
       corrected_fields, corrected_at, needs_review, created_at
from public.residential_rent_listings where needs_review = true
union all
select 'commercial_sale_listings', id, raw_message_id, validation_flags,
       corrected_fields, corrected_at, needs_review, created_at
from public.commercial_sale_listings where needs_review = true
union all
select 'commercial_rent_listings', id, raw_message_id, validation_flags,
       corrected_fields, corrected_at, needs_review, created_at
from public.commercial_rent_listings where needs_review = true
union all
select 'residential_sale_requirements', id, raw_message_id, validation_flags,
       corrected_fields, corrected_at, needs_review, created_at
from public.residential_sale_requirements where needs_review = true
union all
select 'residential_rent_requirements', id, raw_message_id, validation_flags,
       corrected_fields, corrected_at, needs_review, created_at
from public.residential_rent_requirements where needs_review = true
union all
select 'commercial_sale_requirements', id, raw_message_id, validation_flags,
       corrected_fields, corrected_at, needs_review, created_at
from public.commercial_sale_requirements where needs_review = true
union all
select 'commercial_rent_requirements', id, raw_message_id, validation_flags,
       corrected_fields, corrected_at, needs_review, created_at
from public.commercial_rent_requirements where needs_review = true;
