-- Deterministic public collections reference existing public listing records.
-- This is not a second inventory table: collection items are typed listing IDs.
create table if not exists public.public_listing_collections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null,
  collection_type text not null check (collection_type in ('market_slice')),
  locality text not null,
  transaction_type text not null check (transaction_type in ('rent','sale')),
  bhk text,
  listing_count integer not null default 0 check (listing_count >= 0),
  freshness_days integer not null default 30 check (freshness_days between 1 and 365),
  rule_version text not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'published' check (status in ('published','archived'))
);

create table if not exists public.public_listing_collection_items (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.public_listing_collections(id) on delete cascade,
  listing_type text not null check (listing_type in ('residential_rent','residential_sale','commercial_rent','commercial_sale')),
  listing_id bigint not null,
  rank integer not null check (rank > 0),
  score numeric not null default 0,
  reason_codes jsonb not null default '[]'::jsonb,
  generated_at timestamptz not null default now(),
  unique (collection_id, listing_type, listing_id)
);

create index if not exists public_listing_collections_status_idx
  on public.public_listing_collections (status, updated_at desc);
create index if not exists public_listing_collection_items_lookup_idx
  on public.public_listing_collection_items (collection_id, rank);

alter table public.public_listing_collections enable row level security;
alter table public.public_listing_collection_items enable row level security;
do $$ begin
  execute 'create policy service_role_all_public_listing_collections on public.public_listing_collections for all to service_role using (true) with check (true)';
exception when duplicate_object then null; end $$;
do $$ begin
  execute 'create policy service_role_all_public_listing_collection_items on public.public_listing_collection_items for all to service_role using (true) with check (true)';
exception when duplicate_object then null; end $$;

drop view if exists public.public_listing_collections_public;
create view public.public_listing_collections_public with (security_invoker = false) as
select id, slug, title, description, collection_type, locality, transaction_type,
       bhk, listing_count, freshness_days, rule_version, generated_at, updated_at
from public.public_listing_collections
where status = 'published';
grant select on public.public_listing_collections_public to anon, authenticated;

drop view if exists public.public_listing_collection_items_public;
create view public.public_listing_collection_items_public with (security_invoker = false) as
select i.collection_id, c.slug, i.listing_type, i.listing_id, i.rank, i.score,
       i.reason_codes, i.generated_at
from public.public_listing_collection_items i
join public.public_listing_collections c on c.id = i.collection_id
where c.status = 'published';
grant select on public.public_listing_collection_items_public to anon, authenticated;

comment on table public.public_listing_collections is
  'Generated factual market slices; metadata only, never a duplicate inventory source.';
comment on table public.public_listing_collection_items is
  'Typed references to source-backed public listings with reproducible deterministic reasons.';

-- Requirement buckets are workspace-private and are maintained by the same
-- deterministic matcher that writes requirement_matches. They are not exposed
-- through the public collection projections above.
alter table public.match_buckets
  add column if not exists generated_from_requirement_type text,
  add column if not exists generated_from_requirement_id bigint,
  add column if not exists generation_mode text not null default 'manual';
create unique index if not exists match_buckets_generated_requirement_idx
  on public.match_buckets (tenant_id, generated_from_requirement_type, generated_from_requirement_id)
  where generated_from_requirement_type is not null and generated_from_requirement_id is not null;
notify pgrst, 'reload schema';
